---

- name: install mutt 
  yum: pkg=mutt state=installed
  tags: userland

- name: install git 
  yum: pkg=git state=installed
  tags: userland

- name: install figlet 
  yum: pkg=figlet state=installed
  tags: userland

- name: install htop
  yum: pkg=htop state=installed
  tags: userland

#- name: install pico 
  #yum: pkg=pico state=installed
  #tags: userland

- name: install emacs 
  yum: pkg=emacs state=installed
  tags: userland

- name: install irssi
  yum: pkg=irssi state=installed
  tags: userland

- name: install oidentd
  yum: name=oidentd enablerepo=epel state=present

- name: start oidentd
  service: name=oidentd enabled=yes state=started

- name: install git
  yum: pkg=git state=installed

- name: remove existing /etc/skel files
  shell: rm -f /etc/skel/* /etc/skel/.*
  ignore_errors: yes

- name: install skel repository
  git: repo={{skel_repo}}
       dest=/etc/skel
       depth=1
