---

- name: install packages
  yum: pkg={{ item }} state=installed 
  with_items: packages

- name: install epel packages
  yum: pkg={{ item }} state=installed enablerepo=epel
  with_items: epel_packages

- name: start oidentd
  service: name=oidentd enabled=yes state=started

- name: remove existing /etc/skel files
  shell: rm -f /etc/skel/* /etc/skel/.*
  ignore_errors: yes

- name: install skel repository
  git: repo={{skel_repo}}
       dest=/etc/skel
       depth=1
