---

- name: install apache httpd
  yum: pkg=httpd state=installed
  tags: www

- name: install telnet
  yum: pkg=telnet state=installed
  tags: www

- name: install lynx
  yum: pkg=lynx state=installed
  tags: www


# /etc/httpd/conf/httpd.conf
- name: httpd conf
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf owner=root group=root mode=0644
  notify:
     - restart apache
